import Foundation

struct SeedData {

    static func allRecipes() -> [Recipe] {
        [
            jamesHoffmann(),
            invertedBasic(),
            quickMorning(),
            coldBrew(),
            timWendelboe(),
            timWendelboeStronger(),
            lanceHedrickLight(),
            lanceHedrickDark(),
            wacIbarraGaray2018(),
            wacVanBunnik2019(),
            wacMerikanto2021(),
            wacJibbiLittle2022(),
            wacWipvasutt2023(),
            wacStanica2024(),
            wacNemoPop2025()
        ]
    }

    // MARK: - James Hoffmann
    static func jamesHoffmann() -> Recipe {
        let recipe = Recipe(
            id: "james-hoffmann",
            name: "James Hoffmann AeroPress",
            author: "James Hoffmann",
            method: .standard,
            coffeeAmount: 11,
            waterAmount: 200,
            waterTemperature: 95,
            ratio: "1:18",
            totalTime: 150,
            difficulty: .beginner,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "jh-1", order: 1,
                 title: "Preparation",
                 stepDescription: "Set up AeroPress in standard position on your cup. Place a paper filter in the cap and rinse with hot water.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "jh-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 11g of freshly ground coffee (medium-fine, like table salt) into the AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "jh-3", order: 3,
                 title: "Add Water",
                 stepDescription: "Pour 200ml of water heated to 95°C. Cover all the coffee in circular motions.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "jh-4", order: 4,
                 title: "Stir",
                 stepDescription: "Gently stir 3 times in circular motions so all coffee is saturated.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "jh-5", order: 5,
                 title: "Insert Plunger",
                 stepDescription: "Place the plunger on top of the AeroPress to create a vacuum. DON'T press yet!",
                 imageURL: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800",
                 hasTimer: false),
            Step(id: "jh-6", order: 6,
                 title: "Wait",
                 stepDescription: "Let the coffee extract. The vacuum prevents dripping.",
                 imageURL: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800",
                 hasTimer: true, timerDuration: 120),
            Step(id: "jh-7", order: 7,
                 title: "Swirl",
                 stepDescription: "Gently swirl the entire AeroPress so the sediment settles from the sides.",
                 imageURL: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800",
                 hasTimer: false),
            Step(id: "jh-8", order: 8,
                 title: "Press",
                 stepDescription: "Slowly and evenly push the plunger down. Stop when you hear hissing.",
                 imageURL: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "jh-9", order: 9,
                 title: "Done!",
                 stepDescription: "Your coffee is ready! Optionally dilute with a little hot water for an americano style.",
                 imageURL: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Inverted Basic
    static func invertedBasic() -> Recipe {
        let recipe = Recipe(
            id: "inverted-basic",
            name: "Inverted Basic",
            author: "AeroPress Community",
            method: .inverted,
            coffeeAmount: 15,
            waterAmount: 220,
            waterTemperature: 92,
            ratio: "1:15",
            totalTime: 180,
            difficulty: .intermediate,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "ib-1", order: 1,
                 title: "Inverted setup",
                 stepDescription: "Place the plunger in the AeroPress and flip upside down. The plunger should be at level \"1\".",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "ib-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 15g of ground coffee (medium grind) into the inverted AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "ib-3", order: 3,
                 title: "Bloom",
                 stepDescription: "Add 30ml of water and gently stir. Let it \"bloom\" for 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "ib-4", order: 4,
                 title: "Add Remaining Water",
                 stepDescription: "Slowly pour the remaining 190ml of water in circular motions.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: false),
            Step(id: "ib-5", order: 5,
                 title: "Stir",
                 stepDescription: "Stir 5 times back and forth.",
                 imageURL: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "ib-6", order: 6,
                 title: "Steep",
                 stepDescription: "Place the filter cap and wait. Don't forget to rinse the filter before attaching!",
                 imageURL: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800",
                 hasTimer: true, timerDuration: 90),
            Step(id: "ib-7", order: 7,
                 title: "Flip & Press",
                 stepDescription: "Carefully flip the AeroPress onto your cup. Press slowly (30 seconds).",
                 imageURL: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "ib-8", order: 8,
                 title: "Enjoy!",
                 stepDescription: "Your coffee is ready. The inverted method gives a fuller body flavor.",
                 imageURL: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Quick Morning
    static func quickMorning() -> Recipe {
        let recipe = Recipe(
            id: "quick-morning",
            name: "Quick Morning",
            author: "AeroPress Guide",
            method: .standard,
            coffeeAmount: 12,
            waterAmount: 180,
            waterTemperature: 90,
            ratio: "1:15",
            totalTime: 75,
            difficulty: .beginner,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "qm-1", order: 1,
                 title: "Setup",
                 stepDescription: "Set up AeroPress on your cup. Place the filter and rinse.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "qm-2", order: 2,
                 title: "Coffee & Water",
                 stepDescription: "Add 12g of coffee, pour 180ml of water (90°C), stir once.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "qm-3", order: 3,
                 title: "Wait",
                 stepDescription: "Place the plunger and wait 45 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800",
                 hasTimer: true, timerDuration: 45),
            Step(id: "qm-4", order: 4,
                 title: "Press",
                 stepDescription: "Press quickly but controlled.",
                 imageURL: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800",
                 hasTimer: true, timerDuration: 20),
            Step(id: "qm-5", order: 5,
                 title: "Done!",
                 stepDescription: "Fast and delicious coffee for a busy morning!",
                 imageURL: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Cold Brew
    static func coldBrew() -> Recipe {
        let recipe = Recipe(
            id: "cold-brew-aeropress",
            name: "Cold Brew AeroPress",
            author: "AeroPress Guide",
            method: .standard,
            coffeeAmount: 20,
            waterAmount: 200,
            waterTemperature: 20,
            ratio: "1:10",
            totalTime: 225,
            difficulty: .beginner,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "cb-1", order: 1,
                 title: "Preparation",
                 stepDescription: "Set up AeroPress. For cold brew we use more coffee and cold water.",
                 imageURL: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800",
                 hasTimer: false),
            Step(id: "cb-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 20g of coarsely ground coffee (coarse grind, like sea salt).",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "cb-3", order: 3,
                 title: "Add Cold Water",
                 stepDescription: "Pour 200ml of cold water. Stir well so all coffee is saturated.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "cb-4", order: 4,
                 title: "Steep",
                 stepDescription: "Place the plunger and leave for 3 minutes at room temperature. For a stronger taste: up to 5 minutes.",
                 imageURL: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800",
                 hasTimer: true, timerDuration: 180),
            Step(id: "cb-5", order: 5,
                 title: "Press",
                 stepDescription: "Press slowly. Cold brew requires a bit more force.",
                 imageURL: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800",
                 hasTimer: true, timerDuration: 45),
            Step(id: "cb-6", order: 6,
                 title: "Serve",
                 stepDescription: "Add ice and water/milk as desired. Cold brew concentrate is strong!",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Tim Wendelboe Filter
    static func timWendelboe() -> Recipe {
        let recipe = Recipe(
            id: "tim-wendelboe",
            name: "Tim Wendelboe Filter",
            author: "Tim Wendelboe",
            method: .standard,
            coffeeAmount: 14,
            waterAmount: 200,
            waterTemperature: 96,
            ratio: "1:14",
            totalTime: 120,
            difficulty: .beginner,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "tw-1", order: 1,
                 title: "Preparation",
                 stepDescription: "Set up the AeroPress in standard position on your cup. Place a paper filter in the cap and rinse it with hot running water for about 10 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "tw-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 14g of freshly ground coffee (fine filter — around 15-20 clicks on a Comandante grinder).",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "tw-3", order: 3,
                 title: "Add Water",
                 stepDescription: "Pour 200g of water heated to 96°C over all the coffee.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "tw-4", order: 4,
                 title: "First Stir",
                 stepDescription: "Stir 3 times back and forth. Exactly 3 — fewer means under-extracted, more means over-extracted.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: false),
            Step(id: "tw-5", order: 5,
                 title: "Steep",
                 stepDescription: "Place the plunger on top of the AeroPress to prevent water dripping through the filter. DON'T press — just let it sit for 60 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 60),
            Step(id: "tw-6", order: 6,
                 title: "Second Stir",
                 stepDescription: "Remove the plunger and stir again exactly 3 times back and forth.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: false),
            Step(id: "tw-7", order: 7,
                 title: "Press",
                 stepDescription: "Replace the plunger and press slowly using your body weight. Press all the way through the hiss — that's fine for this recipe.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "tw-8", order: 8,
                 title: "Enjoy",
                 stepDescription: "A clean, balanced filter coffee — the recipe served at Wendelboe's coffee bar in Oslo.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Tim Wendelboe Stronger
    static func timWendelboeStronger() -> Recipe {
        let recipe = Recipe(
            id: "tim-wendelboe-stronger",
            name: "Tim Wendelboe Stronger",
            author: "Tim Wendelboe",
            method: .standard,
            coffeeAmount: 14,
            waterAmount: 130,
            waterTemperature: 100,
            ratio: "1:9",
            totalTime: 90,
            difficulty: .intermediate,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "tws-1", order: 1,
                 title: "Preparation",
                 stepDescription: "Place the AeroPress on your cup. Insert a paper filter and rinse it. Prepare boiling water — straight off the kettle (full boil).",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "tws-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 14g of finely ground coffee into the AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "tws-3", order: 3,
                 title: "Add Boiling Water",
                 stepDescription: "Pour 130g of water straight from the kettle (~100°C). Quick and decisive — temperature matters here.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "tws-4", order: 4,
                 title: "Vigorous Stir",
                 stepDescription: "Stir 3 times — strong and fast. The goal is maximum agitation for a strong extraction.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "tws-5", order: 5,
                 title: "Press",
                 stepDescription: "Insert the plunger and press immediately, using full body weight. The press takes about 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "tws-6", order: 6,
                 title: "Done",
                 stepDescription: "A strong, concentrated cup similar to a moka pot. Wendelboe's recipe for espresso-style AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Lance Hedrick Light Roast
    static func lanceHedrickLight() -> Recipe {
        let recipe = Recipe(
            id: "lance-hedrick-light",
            name: "Lance Hedrick — Light Roast",
            author: "Lance Hedrick",
            method: .inverted,
            coffeeAmount: 15,
            waterAmount: 200,
            waterTemperature: 91,
            ratio: "1:13",
            totalTime: 180,
            difficulty: .intermediate,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "lhl-1", order: 1,
                 title: "Setup (inverted)",
                 stepDescription: "Set up the AeroPress in inverted position. The plunger should be at level '1'. Prepare a separate cup with 80ml of hot water for the bypass at the end.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "lhl-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 15g of medium-coarse ground coffee (~1000 microns, around 30 clicks on a Comandante grinder).",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "lhl-3", order: 3,
                 title: "Pour All Water at Once",
                 stepDescription: "Pour all 120g of water at 91°C in one go — every grain of coffee should be saturated in a single motion.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "lhl-4", order: 4,
                 title: "Vigorous Stir",
                 stepDescription: "Stir aggressively for 10 seconds for an even extraction.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "lhl-5", order: 5,
                 title: "Steep",
                 stepDescription: "Let it sit until the 1:00 mark (50 seconds after the stir).",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 50),
            Step(id: "lhl-6", order: 6,
                 title: "Cap It",
                 stepDescription: "Wet a paper filter in the cap with hot water and attach the cap to the AeroPress. Get the cup ready for the flip.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "lhl-7", order: 7,
                 title: "Flip & Press",
                 stepDescription: "Carefully flip the AeroPress onto the cup. Press slowly — the press should last a full minute.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 60),
            Step(id: "lhl-8", order: 8,
                 title: "Bypass",
                 stepDescription: "Add the 80ml of hot water (bypass) to the cup. This gives you a brighter, vibrant cup that preserves the acidity typical of light roasts.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - Lance Hedrick Dark Roast
    static func lanceHedrickDark() -> Recipe {
        let recipe = Recipe(
            id: "lance-hedrick-dark",
            name: "Lance Hedrick — Dark Roast",
            author: "Lance Hedrick",
            method: .inverted,
            coffeeAmount: 30,
            waterAmount: 120,
            waterTemperature: 80,
            ratio: "1:4",
            totalTime: 120,
            difficulty: .advanced,
            isCustom: false
        )
        recipe.steps = [
            Step(id: "lhd-1", order: 1,
                 title: "Setup (inverted)",
                 stepDescription: "Set up the AeroPress in inverted position with the plunger at level '1'. Prepare water at 80°C — the low temperature is key for dark roasts.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "lhd-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 30g of very coarsely ground coffee (~1200 microns, around 35 clicks on a Comandante or 65 on a 1ZPRESSO ZP6). The large dose and coarse grind are intentional.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "lhd-3", order: 3,
                 title: "Pour All Water",
                 stepDescription: "Pour all 120g of water at 80°C in one go.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "lhd-4", order: 4,
                 title: "Vigorous Stir",
                 stepDescription: "Stir aggressively for 10 seconds for an even extraction.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "lhd-5", order: 5,
                 title: "Steep",
                 stepDescription: "Let it sit until 1:00 (50 seconds after the stir). The low temperature and coarse grind give a clean, low-bitterness extraction.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 50),
            Step(id: "lhd-6", order: 6,
                 title: "Cap It",
                 stepDescription: "Wet a paper filter in the cap and attach it to the AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "lhd-7", order: 7,
                 title: "Flip & Press",
                 stepDescription: "Carefully flip the AeroPress onto the cup and press slowly. Press over about 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "lhd-8", order: 8,
                 title: "Bypass (optional)",
                 stepDescription: "Optionally dilute with hot water. This recipe is designed specifically for dark roasts, decaf, baked or older coffees where you want to soften the bitterness.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2018 — Carolina Ibarra Garay (USA)
    static func wacIbarraGaray2018() -> Recipe {
        let recipe = Recipe(
            id: "wac-ibarra-garay-2018",
            name: "Carolina Ibarra Garay 2018",
            author: "Carolina Ibarra Garay",
            method: .inverted,
            coffeeAmount: 35,
            waterAmount: 300,
            waterTemperature: 85,
            ratio: "1:9",
            totalTime: 90,
            difficulty: .intermediate,
            isCustom: false,
            sourceYear: 2018,
            sourceCountry: "USA",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac18-1", order: 1,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position. Rinse a paper filter with hot water.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac18-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Pour 35g of medium-fine ground coffee into the chamber.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac18-3", order: 3,
                 title: "Pour Water",
                 stepDescription: "Pour 200g of water at 85°C over 30 seconds. Start the timer.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac18-4", order: 4,
                 title: "Vigorous Stir",
                 stepDescription: "Stir vigorously with a wooden stick or spoon for 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac18-5", order: 5,
                 title: "Cap and Flip",
                 stepDescription: "Attach the cap with the rinsed filter, flip the AeroPress onto the carafe, and press for 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac18-6", order: 6,
                 title: "Dilute",
                 stepDescription: "Add 60g of water at 85°C and 40g of room-temperature water.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac18-7", order: 7,
                 title: "Serve",
                 stepDescription: "Don't preheat the cup — serve immediately at the lower temperature so the aromas read more clearly.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2019 — Wendelien van Bunnik (Netherlands)
    static func wacVanBunnik2019() -> Recipe {
        let recipe = Recipe(
            id: "wac-van-bunnik-2019",
            name: "Wendelien van Bunnik 2019",
            author: "Wendelien van Bunnik",
            method: .inverted,
            coffeeAmount: 30,
            waterAmount: 220,
            waterTemperature: 92,
            ratio: "1:7",
            totalTime: 60,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2019,
            sourceCountry: "Netherlands",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac19-1", order: 1,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position. Rinse a paper filter and set it aside on the cap.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac19-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 30g of coarsely ground coffee to the chamber.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac19-3", order: 3,
                 title: "Fast Pour",
                 stepDescription: "Pour 100g of water at 92°C in 10 seconds. Start the timer.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac19-4", order: 4,
                 title: "Aggressive Stir",
                 stepDescription: "Stir hard 20 times in 10 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac19-5", order: 5,
                 title: "Attach the Cap",
                 stepDescription: "Place the cap with the rinsed filter on the chamber and gently squeeze out excess air.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac19-6", order: 6,
                 title: "Flip and Press",
                 stepDescription: "At 0:40 flip the AeroPress and slowly press all the coffee through (about 60g of extract).",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 20),
            Step(id: "wac19-7", order: 7,
                 title: "Dilute",
                 stepDescription: "Add 100g of water to dilute. Add more if you want a softer cup.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac19-8", order: 8,
                 title: "Cool and Serve",
                 stepDescription: "Stir and decant into another cup so the temperature drops to about 60°C, where the flavours open up.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2021 — Tuomas Merikanto (Finland)
    static func wacMerikanto2021() -> Recipe {
        let recipe = Recipe(
            id: "wac-merikanto-2021",
            name: "Tuomas Merikanto 2021",
            author: "Tuomas Merikanto",
            method: .inverted,
            coffeeAmount: 18,
            waterAmount: 200,
            waterTemperature: 80,
            ratio: "1:11",
            totalTime: 120,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2021,
            sourceCountry: "Finland",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac21-1", order: 1,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position and add 18g of medium-fine ground coffee.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac21-2", order: 2,
                 title: "First Pour",
                 stepDescription: "Start the timer and pour 50g of water at 80°C over the first 10 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac21-3", order: 3,
                 title: "Gentle Stir",
                 stepDescription: "Stir very gently 3 times back and forth.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 5),
            Step(id: "wac21-4", order: 4,
                 title: "Second Pour",
                 stepDescription: "Over the next 15 seconds top up to 200g total at the same temperature.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 15),
            Step(id: "wac21-5", order: 5,
                 title: "Wait",
                 stepDescription: "Let the coffee rest until 0:50.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 20),
            Step(id: "wac21-6", order: 6,
                 title: "Second Stir",
                 stepDescription: "Gently stir 3 more times back and forth.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 5),
            Step(id: "wac21-7", order: 7,
                 title: "Cap It",
                 stepDescription: "At 1:00 squeeze out excess air and attach the cap with the rinsed filter.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac21-8", order: 8,
                 title: "Wait Until Flip",
                 stepDescription: "Let the AeroPress rest until 1:40.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 35),
            Step(id: "wac21-9", order: 9,
                 title: "Flip and Press",
                 stepDescription: "Place the cup on the chamber, flip the AeroPress, and press gently to 2:00.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 20),
            Step(id: "wac21-10", order: 10,
                 title: "Swirl and Serve",
                 stepDescription: "Swirl the cup so the temperature drops slightly before serving.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2022 — Jibbi Little (Australia)
    static func wacJibbiLittle2022() -> Recipe {
        let recipe = Recipe(
            id: "wac-jibbi-little-2022",
            name: "Jibbi Little 2022",
            author: "Jibbi Little",
            method: .inverted,
            coffeeAmount: 18,
            waterAmount: 150,
            waterTemperature: 92,
            ratio: "1:8",
            totalTime: 130,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2022,
            sourceCountry: "Australia",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac22-1", order: 1,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position and rinse a paper filter (set it aside on the cap).",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac22-2", order: 2,
                 title: "Add Coffee",
                 stepDescription: "Add 18g of medium-coarse ground coffee. Sift out the finest particles if you wish.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac22-3", order: 3,
                 title: "Pour Water",
                 stepDescription: "Start the timer and pour 94ml of water at 92°C.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "wac22-4", order: 4,
                 title: "Stir",
                 stepDescription: "Stir gently 35 times in a circular motion.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: false),
            Step(id: "wac22-5", order: 5,
                 title: "Wait Until 1:20",
                 stepDescription: "Let the coffee rest until the 1:20 mark.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 80),
            Step(id: "wac22-6", order: 6,
                 title: "Cap It",
                 stepDescription: "Attach the cap with the rinsed filter and gently squeeze out excess air.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac22-7", order: 7,
                 title: "Flip and Press",
                 stepDescription: "At 1:30 flip the AeroPress onto the carafe and press slowly for 30 seconds. You should yield about 60g of concentrate.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac22-8", order: 8,
                 title: "Bypass",
                 stepDescription: "Add 90ml of water at 90°C to the concentrate to bring it to 150g total. Stir and serve.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2023 — Tay Wipvasutt (Thailand)
    static func wacWipvasutt2023() -> Recipe {
        let recipe = Recipe(
            id: "wac-wipvasutt-2023",
            name: "Tay Wipvasutt 2023",
            author: "Tay Wipvasutt",
            method: .inverted,
            coffeeAmount: 18,
            waterAmount: 155,
            waterTemperature: 92,
            ratio: "1:9",
            totalTime: 125,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2023,
            sourceCountry: "Thailand",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac23-1", order: 1,
                 title: "Prepare the Coffee",
                 stepDescription: "Grind 18g of medium-coarse coffee. Set 2g aside — you'll add it later.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac23-2", order: 2,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position and add 16g of coffee.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac23-3", order: 3,
                 title: "First Pour",
                 stepDescription: "Pour 100g of hot water and start the timer.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "wac23-4", order: 4,
                 title: "First Stir",
                 stepDescription: "At 0:30 stir for 5 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac23-5", order: 5,
                 title: "Add Remaining Coffee",
                 stepDescription: "At 0:45 add the remaining 2g of coffee to the chamber.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: true, timerDuration: 15),
            Step(id: "wac23-6", order: 6,
                 title: "Second Stir",
                 stepDescription: "At 0:55 stir for another 5 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac23-7", order: 7,
                 title: "Cap It",
                 stepDescription: "Pull the plunger up gently to release excess air, then attach the cap with the rinsed filter.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac23-8", order: 8,
                 title: "Flip and Press",
                 stepDescription: "At 1:35 carefully flip the AeroPress and press for 30 seconds. You should yield about 75g.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac23-9", order: 9,
                 title: "Dilute",
                 stepDescription: "Add 40g of room-temperature water, then 40g of hot water (about 155g total).",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac23-10", order: 10,
                 title: "Serve",
                 stepDescription: "Taste and adjust strength with more water if needed.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2024 — George Stanica (Romania)
    static func wacStanica2024() -> Recipe {
        let recipe = Recipe(
            id: "wac-stanica-2024",
            name: "George Stanica 2024",
            author: "George Stanica",
            method: .inverted,
            coffeeAmount: 18,
            waterAmount: 155,
            waterTemperature: 96,
            ratio: "1:9",
            totalTime: 150,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2024,
            sourceCountry: "Romania",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac24-1", order: 1,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in inverted position with the plunger near the 4 mark. Add 18g of medium-coarse ground coffee.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac24-2", order: 2,
                 title: "First Pour",
                 stepDescription: "Start the timer and pour 50g of water at 96°C in 5–6 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 6),
            Step(id: "wac24-3", order: 3,
                 title: "Bloom",
                 stepDescription: "Let the coffee bloom for 30 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac24-4", order: 4,
                 title: "Second Pour",
                 stepDescription: "Pour another 50g of water at 96°C in 5–6 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 6),
            Step(id: "wac24-5", order: 5,
                 title: "NSEW Stir",
                 stepDescription: "Stir gently for 10 seconds moving N–S–E–W. Hold the spoon vertically and only move the top layer.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac24-6", order: 6,
                 title: "Prepare the Filter",
                 stepDescription: "Rinse a paper filter with hot water while the coffee rests.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac24-7", order: 7,
                 title: "Wait Until 1:20",
                 stepDescription: "Let the coffee rest until 1:20 total time.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 30),
            Step(id: "wac24-8", order: 8,
                 title: "Cap It",
                 stepDescription: "Attach the cap with the rinsed filter and gently squeeze out excess air over about 10 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: true, timerDuration: 10),
            Step(id: "wac24-9", order: 9,
                 title: "Flip and Press",
                 stepDescription: "Swirl the AeroPress, flip it onto the carafe, and start pressing slowly at 1:35. Press over 30–40 seconds for about 78g of extract.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 40),
            Step(id: "wac24-10", order: 10,
                 title: "First Dilution",
                 stepDescription: "Add hot water from the kettle to reach about 130–135g total.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac24-11", order: 11,
                 title: "Second Dilution",
                 stepDescription: "Add 20–30g of room-temperature water. Stir and serve.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }

    // MARK: - WAC 2025 — Némo Pop (Australia)
    static func wacNemoPop2025() -> Recipe {
        let recipe = Recipe(
            id: "wac-nemo-pop-2025",
            name: "Némo Pop 2025",
            author: "Némo Pop",
            method: .standard,
            coffeeAmount: 18,
            waterAmount: 170,
            waterTemperature: 84,
            ratio: "1:9",
            totalTime: 70,
            difficulty: .advanced,
            isCustom: false,
            sourceYear: 2025,
            sourceCountry: "Australia",
            sourceBadge: "WAC Champion"
        )
        recipe.steps = [
            Step(id: "wac25-1", order: 1,
                 title: "Prepare the Bypass Water",
                 stepDescription: "Pour 70g of room-temperature water (about 50°C) directly into the carafe under the AeroPress.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "wac25-2", order: 2,
                 title: "Set Up the AeroPress",
                 stepDescription: "Place the AeroPress in upright position (filter down) on the carafe. Rinse two paper filters.",
                 imageURL: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                 hasTimer: false),
            Step(id: "wac25-3", order: 3,
                 title: "Add Coffee",
                 stepDescription: "Add 18g of medium-fine ground coffee. Sift out the finest particles if you wish.",
                 imageURL: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                 hasTimer: false),
            Step(id: "wac25-4", order: 4,
                 title: "Pour Water",
                 stepDescription: "Start the timer and pour 100g of water at 84°C, making sure all the grounds are saturated.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: false),
            Step(id: "wac25-5", order: 5,
                 title: "NSEW Stir",
                 stepDescription: "At 0:25 stir N–S–N–S, then W–E–W–E.",
                 imageURL: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                 hasTimer: true, timerDuration: 25),
            Step(id: "wac25-6", order: 6,
                 title: "Press",
                 stepDescription: "At 0:50 begin pressing gently. Press for about 20 seconds.",
                 imageURL: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                 hasTimer: true, timerDuration: 25),
            Step(id: "wac25-7", order: 7,
                 title: "Serve",
                 stepDescription: "The bypass water in the carafe has already diluted the cup. Stir and serve.",
                 imageURL: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                 hasTimer: false)
        ]
        return recipe
    }
}
